package com.mhallman.skateshop.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ClientManager {

	/**
	 * Initialization of variables used in ClientManager class
	 */
	private Statement statement;
	private PreparedStatement addClientStmt;
	private PreparedStatement deleteAllClientsStmt;
	private PreparedStatement getAllClientsStmt;
	private dbConnect dbconn = new dbConnect();
	private Connection conn = dbconn.getConnection();
	private ResultSet rs;
	private String createTableClient = "CREATE TABLE Client(id_client bigint GENERATED BY DEFAULT AS IDENTITY, first_name varchar(20), second_name varchar(20), bigint phone_number)";
	
	/**
	 * Basic constructor for ClientManager class
	 * - creates table Client if not exists
	 * - prepares statements 
	 */
	public ClientManager(){
		try {
			rs = conn.getMetaData().getTables(null, null, null,null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Client".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			if (!tableExists){
				statement.executeUpdate(createTableClient);
			}

			addClientStmt = conn.prepareStatement("INSERT INTO Client (first_name,second_name,phone_number) VALUES (?, ?, ?)");
			deleteAllClientsStmt = conn.prepareStatement("DELETE FROM Client");
			getAllClientsStmt = conn.prepareStatement("SELECT id_client, first_name,second_name, phone_number FROM Client");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	
}
