package com.mhallman.skateshop.service;

import java.sql.Connection;
import java.sql.PreparedStatement;

public class ClientManager {

	
	private PreparedStatement addClientStmt;
	private PreparedStatement deleteAllClientsStmt;
	private PreparedStatement getAllClientsStmt;
	private dbConnect dbconn = new dbConnect();
	private Connection conn = dbconn.getConnection();
	
	
	private String createTableClient = "CREATE TABLE Client(id_client bigint GENERATED BY DEFAULT AS IDENTITY, first_name varchar(20), second_name varchar(20), bigint phone_number)";
	
	
	public ClientManager(){
		
	}

	
}
