package com.mhallman.skateshop.service;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.mhallman.skateshop.domain.Client;
import com.mhallman.skateshop.domain.Purchase;

public class PurchaseManager {


	/**
	 * Initialization of variables used in PurchaseManager class
	 */
	private PreparedStatement addPurchaseStmt;
	private PreparedStatement updatePurchasesStmt;
	private PreparedStatement deletePurchaseStmt;
	private PreparedStatement deleteAllPurchasesStmt;
	private PreparedStatement deleteAllPurchasesOfClientStmt;
	private PreparedStatement getAllPurchasesStmt;
	private PreparedStatement getAllPurchasesOfClientStmt;
	private dbConnect dbconn = new dbConnect();
	private Connection conn = dbconn.getConnection();
	private Statement statement;
	private Statement statement2;

	private ResultSet rs;
	private String alterTablePurchase = "ALTER TABLE Purchase ADD CONSTRAINT id_clientfk FOREIGN KEY (id_client) REFERENCES Client(id_client) ON DELETE CASCADE";
	private String createTablePurchase = "CREATE TABLE Purchase(id_purchase bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_client bigint, date varchar(11))";
	
	/**
	 * Basic constructor for PurchaseManager class
	 * - creates table Product if not exists
	 * - prepares statements 
	 */
	public PurchaseManager(){
		try {
			if(conn!=null){
				System.out.print("Connected to database\n");
			}
			rs = conn.getMetaData().getTables(null, null, null,null);
			boolean tablePurchaseExists = false;
			while (rs.next()) {
				if ("Purchase".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tablePurchaseExists = true;
					break;
				}
			}
			
			if (!tablePurchaseExists){
				statement = conn.createStatement();
				statement2 = conn.createStatement();
				statement.executeUpdate(createTablePurchase);
				statement2.executeUpdate(alterTablePurchase);
			}

			addPurchaseStmt = conn.prepareStatement("INSERT INTO Purchase (id_client,date) VALUES (?, ?)");
			updatePurchasesStmt = conn.prepareStatement("UPDATE Purchase SET date=? WHERE id_client= ?");
			deletePurchaseStmt = conn.prepareStatement("DELETE FROM Purchase WHERE id_client= ?");
			deleteAllPurchasesStmt = conn.prepareStatement("DELETE FROM Purchase");
			deleteAllPurchasesOfClientStmt = conn.prepareStatement("DELETE FROM Purchase WHERE id_client=?");
			getAllPurchasesStmt = conn.prepareStatement("SELECT id_purchase, id_client,date FROM Purchase");
			getAllPurchasesOfClientStmt = conn.prepareStatement("SELECT id_purchase,date FROM Purchase WHERE id_client=?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	
	/**
	 * Method deleting all Purchases from Database
	 */
	public void deletePurchases(){
		try {
			deleteAllPurchasesStmt.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	
	/**
	 * Method updating Purchase or Purchases in Database
	 * @param date
	 * @param id_client
	 * @return
	 */
	public int updatePurchases(String date, Client client){
		int count=0;
		
		try {
			updatePurchasesStmt.setString(1, date);
			updatePurchasesStmt.setLong(2, client.getId_client());
			count=updatePurchasesStmt.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return count;
	}
	
	/**
	 * Method deleting Purchases done by specific Client from Database
	 * @param id_client
	 */
	public void deletePurchase(Client client){
		try {
			deletePurchaseStmt.setLong(1, client.getId_client());
			deletePurchaseStmt.execute();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * 
	 */
	public void deletePurchasesOfClient(Client client){
		try {
			deleteAllPurchasesOfClientStmt.setLong(1, client.getId_client());
			deleteAllPurchasesOfClientStmt.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * Method adding Purchase to Database
	 * @param purchase
	 * @return
	 */
	public int addPurchase(Purchase purchase){
		int count=0;
		try {
			addPurchaseStmt.setLong(1, purchase.getId_client());
			addPurchaseStmt.setString(2, purchase.getDate());
			count=addPurchaseStmt.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return count;	
	}
	
	/**
	 * Method getting all Purchases from Database
	 * @return
	 */
	public List<Purchase> getAllPurchases(){
		ArrayList<Purchase> Purchases = new ArrayList<Purchase>();
		
		try {
			ResultSet rs = getAllPurchasesStmt.executeQuery();
			while(rs.next()){
				Purchase purchase = new Purchase();
				purchase.setId_purchase(rs.getLong("id_purchase"));
				purchase.setId_client(rs.getLong("id_client"));
				purchase.setDate(rs.getString("date"));
				Purchases.add(purchase);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return Purchases;
	}
	
	
	/**
	 * Method getting all Purchases done by specific Client from Database
	 * @param id_client
	 * @return
	 */
	public List<Purchase> getAllPurchasesOfClient(Client client){
		ArrayList<Purchase> Purchases = new ArrayList<Purchase>();
		try {
			getAllPurchasesOfClientStmt.setLong(1, client.getId_client());
			ResultSet rs = getAllPurchasesOfClientStmt.executeQuery();
			while(rs.next()){
				Purchase purchase = new Purchase();
				purchase.setId_purchase(rs.getLong("id_purchase"));
				purchase.setId_client(client.getId_client());
				purchase.setDate(rs.getString("date"));
				Purchases.add(purchase);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return Purchases;
	}
	
	
}
